python -m pip install flask -i http://binario.caixa:8081/repository/pypi-repo/simple --trusted-host binario.caixa
    python -m pip install waitress -i http://binario.caixa:8081/repository/pypi-repo/simple --trusted-host binario.caixa
    python -m pip install watchdog -i http://binario.caixa:8081/repository/pypi-repo/simple --trusted-host binario.caixa
    python -m pip install ldap3 -i http://binario.caixa:8081/repository/pypi-repo/simple --trusted-host binario.caixa
    python -m pip install cryptography -i http://binario.caixa:8081/repository/pypi-repo/simple --trusted-host binario.caixa
    python -m pip install flask-jwt -i http://binario.caixa:8081/repository/pypi-repo/simple --trusted-host binario.caixa
    python -m pip install requests -i http://binario.caixa:8081/repository/pypi-repo/simple --trusted-host binario.caixa
    python -m pip install markdown -i http://binario.caixa:8081/repository/pypi-repo/simple --trusted-host binario.caixa
    python -m pip install flask_cors -i http://binario.caixa:8081/repository/pypi-repo/simple --trusted-host binario.caixa
    python -m pip install pandas -i http://binario.caixa:8081/repository/pypi-repo/simple --trusted-host binario.caixa
    python -m pip install openpyxl -i http://binario.caixa:8081/repository/pypi-repo/simple --trusted-host binario.caixa
    python -m pip install colorama -i http://binario.caixa:8081/repository/pypi-repo/simple --trusted-host binario.caixa
    python -m pip install Flask-Bootstrap -i http://binario.caixa:8081/repository/pypi-repo/simple --trusted-host binario.caixa
    python -m pip install Flask-FontAwesome -i http://binario.caixa:8081/repository/pypi-repo/simple --trusted-host binario.caixa
    python -m pip install python-dotenv -i http://binario.caixa:8081/repository/pypi-repo/simple --trusted-host binario.caixa