pip install flask
pip install waitress
pip install watchdog
pip install ldap3
pip install cryptography
pip install flask-jwt
pip install requests
pip install markdown
pip install flask_cors
pip install pandas
pip install openpyxl
pip install colorama
pip install Flask-Bootstrap
pip install Flask-FontAwesome
pip install python-dotenv